config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/boss', as: 'rails_admin'
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  root 'boards#index'
  resources :posts
  resources :comments
  resources :boards
  resources :pins

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    has_many :posts
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/pin.rb
class Pin < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
    validates :board_id, presence: true
    has_many :comments
    belongs_to :user
    belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
  enum status: [:guest, :member, :manager, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, only: [:create]
      
    def create
        comment = Comment.new
        comment.post_id = params[:post_id]
        comment.user_id = current_user.id
        comment.content = params[:content]
        comment.save
        redirect_to post_path(comment.post)
    end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  def index
    @pins = Pin.all
  end

  def new
    @pin = Pin.new
  end
  
  def create
    @pin = Pin.new(pin_params)
    if @pin.save
      redirect_to pins_path
    else
      render :new
    end
  end

  private
  
  def pin_params
    params.require(:pin).permit(:title, :lat, :lng)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit]
  
  def index
    @posts = Post.order(id: :desc).all
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
  end
  
  private
  
  def post_params
    params.require(:post).permit([:title, :board_id, :content])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/boards/index.html.erb
<div class="row">
  <% @boards.each do |board| %>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= link_to board.title, board_path(board) %></h3>
        </div>
        <table class="table">
          <% board.posts.last(5).each do |post| %>
          <tr>
            <td><%= post.user.name %></td>
            <td><%= link_to post.title, post_path(post) %></td>
            <td><%= post.created_at.strftime("%A, %d %b %Y %l:%M %p") %></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/views/boards/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @board.title %></h3>
      </div>
      <table class="table">
        <% @board.posts.last(5).each do |post| %>
        <tr>
          <td><%= post.user.try(:name) %></td>
          <td><%= link_to post.title, post_path(post) %></td>
          <td><%= post.created_at.strftime("%A, %d %b %Y %l:%M %p") %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

<%= link_to '게시판 리스트 보기', boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ewhaboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">이화보드</a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to '새글쓰기', new_post_path %></li>
            <% Board.all.each do |board| %>
              <li><%= link_to board.title, board_path(board) %></li>
            <% end %>
            <li><%= link_to '지도보기', pins_path %></li>
            <li><%= link_to '핀꼽기', new_pin_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to '정보수정', edit_user_registration_path %></li>
              <li><%= link_to '로그아웃', destroy_user_session_path, method: 'delete' %></li>
            <% else %>
              <li><%= link_to '로그인', new_user_session_path %></li>
              <li><%= link_to '회원가입', new_user_registration_path %></li>
            <% end %>            
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <% if flash[:alert].present? %>
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <%= flash[:alert] %>
        </div>
      <% end %>
      
      <%= yield %>
    </div>

  </body>
</html>

app/views/pins/index.html.erb
<div class="row">
    <div class="col-md-12">
        <div id="map" style="width: 100%; height: 400px;"></div>
    </div>
</div>
<script>
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: <%=@pins.first.lat.to_f%>, lng: <%=@pins.first.lng.to_f%>},
      zoom: 16
    });
    <% @pins.each do |pin| %>
        var marker = new google.maps.Marker({
          position: {lat: <%=pin.lat.to_f%>, lng: <%=pin.lng.to_f%>},
          map: map,
          title: "<%=pin.title%>"
        });
    <% end %>
  }
</script>
<script src="//maps.googleapis.com/maps/api/js?key=<%=ENV['GMAP_API_KEY']%>&callback=initMap" async defer></script>

app/views/pins/new.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <%= simple_form_for @pin do |f| %>
            <%= f.input :title %>
            <%= f.gmap_coordinate_picker :api_key => ENV['GMAP_API_KEY'], :lat_column => 'lat', :lng_column => 'lng' , :zoom_level => 16, :default_coordinates => [37.562079, 126.946829], autocomplete: { enable: true, class: 'form-control' }  %>
            <%= f.button :submit %>
        <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>이화 게시판</h1>

<h2>게시글</h2>
<ul>
    <% @posts.each do |post| %>
        <li>
            <h3><%= post.title %></h3>
            <h4>작성자: <%= post.try(:user).try(:name) %></h4>
            <p><%= post.try(:content).try(:html_safe) %></p>
            <h4>코멘트</h4>
            <%= form_tag comments_path do %>
                <%= hidden_field_tag :post_id, post.id %>
                <%= text_area_tag :content, nil, placeholder: '내용' %>
                <%= submit_tag '작성' %>
            <% end %>
            <ul>
                <% post.comments.each do |comment| %>
                    <li><%= comment.try(:user).try(:name) %> : <%= comment.content %></li>
                <% end %>
            </ul>
        </li>
    <% end %>
</ul>

app/views/posts/new.html.erb
<h2>포스팅하기</h2>
<%= simple_form_for @post do |f| %>
    <%= f.input :board_id, collection: Board.all, prompt: '게시판을 선택하세요' %>
    <%= f.input :title %>
    <%= f.cktext_area :content, cols: 40, ckeditor: { uiColor: '#AADC6E', toolbar: 'mini' } %>
    <%= f.button :submit %>
<% end %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @post.title %></h3>
        <small><%= @post.user.try(:name) %> <%= @post.created_at %></small>
      </div>
      <div class="panel-body">
        <%= @post.try(:content).try(:html_safe) %>
      </div>

      <table class="table">
        <% @post.comments.each do |comment| %>
          <tr>
            <td><%= comment.try(:user).try(:name) %></td>
            <td><%= comment.content %></td>
          </tr>
        <% end %>
        <%= form_tag comments_path do %>
        <%= hidden_field_tag :post_id, @post.id %>
        <tr>
          <td></td>
          <td>
            <%= text_field_tag :content, nil, placeholder: '내용' %>
            <%= submit_tag '작성' %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>